language: python
services:
  - postgresql
python:
  - "3.7"
before_install:
 - sudo apt-get update -qq
before_script:
  - psql -c 'create database travis_ci_test_depsysif;' -U postgres
install:
  - pip install -U wheel setuptools
  - pip install codecov pytest-cov
  - pip install psycopg2
  - pip install -r requirements.txt
  - python setup.py develop
script: pytest --cov=./
after_success:
  - codecov
